name: Deploy to Firebase Hosting on PR
'on': pull_request

jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.8.x
          cache: npm

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.9'
          bundler-cache: true

      - name: Install npm dependencies
        run: npm ci

      - name: Build JavaScript
        run: npm run js:build

      - name: Build Jekyll
        run: bundle exec jekyll build --future

      - name: Deploy Preview to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MEDDLE_B24F1 }}'
          projectId: meddle-b24f1
          firebaseToolsVersion: v13.23.1